Message: 
    Hi $FN,

Your course is at
	http://webwork.champlainww.ca/webwork2/

Your login name is $LOGIN and your initial password is $SID

You should change your password, once you have logged in, by clicking on the
password/email link in the upper left.  After entering your new password,
press the Change User Options button to save your change.

Some help pages about WeBWorK are at
	http://webwork.maa.org/wiki/Category:Students

Have fun.

